/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Symbols
         * @description Broker instruments with their contract specification.
         */
        get: operations["get_symbols_api_symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/{symbol}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description What data is cached for this instrument, and how healthy it is.
         */
        get: operations["get_coverage_api_symbols__symbol__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Strategy
         * @description Validates a spec without saving it. The errors are the human-readable ones.
         */
        post: operations["validate_strategy_api_strategies_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/edge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Edge
         * @description Gate zero: does the signal beat the spread, before even talking SL/TP?
         */
        post: operations["post_edge_api_edge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Backtest
         * @description Launches a backtest. If it takes over two seconds the run_id returns immediately.
         */
        post: operations["post_backtest_api_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete Run */
        delete: operations["delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Equity
         * @description Equity curve and drawdown, reduced to ~`points` points.
         *
         *     The drawdown is computed on the **whole** series and only then are the
         *     points reduced, otherwise the minimum would be measured on an already
         *     pruned curve.
         */
        get: operations["get_equity_api_runs__run_id__equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trades */
        get: operations["get_trades_api_runs__run_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Runs
         * @description Curves aligned on the same axis and metrics side by side.
         *
         *     The curves are normalized to 100 at the start of their own period: two
         *     runs with different initial equity, or over different periods, stay
         *     comparable.
         */
        post: operations["compare_runs_api_runs_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/walkforward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Walkforward
         * @description Optimize in-sample, apply out-of-sample, one window at a time.
         */
        post: operations["post_walkforward_api_validation_walkforward_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/permutation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Permutation
         * @description The real result against random entries and against permuted price paths.
         */
        post: operations["post_permutation_api_validation_permutation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/multiple-testing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Multiple Testing
         * @description What the observed Sharpe is worth given how many configurations were tried.
         */
        post: operations["post_multiple_testing_api_validation_multiple_testing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/tick-resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Tick Resolve
         * @description Ambiguous trades settled with tick data, or a plain statement that they cannot be.
         */
        post: operations["post_tick_resolve_api_validation_tick_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Batch
         * @description The same spec across many instruments, and whether they agree.
         */
        post: operations["post_batch_api_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Screen
         * @description Starts a screening campaign and returns the job to poll.
         */
        post: operations["post_screen_api_screen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screen/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screen */
        get: operations["get_screen_api_screen__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmbiguityPriorOut
         * @description A-priori share of trades a bar-resolution backtest cannot settle.
         */
        AmbiguityPriorOut: {
            /** Applicable */
            applicable: boolean;
            /** Reason */
            reason?: string | null;
            /** Stop Points */
            stop_points?: number | null;
            /** Target Points */
            target_points?: number | null;
            /** Stop Points Std */
            stop_points_std?: number | null;
            /** Target Points Std */
            target_points_std?: number | null;
            /** Level Distance Points */
            level_distance_points?: number | null;
            /** Nearest Level Points */
            nearest_level_points?: number | null;
            /** Mean Bar Range Points */
            mean_bar_range_points?: number | null;
            /** Both Reachable Share */
            both_reachable_share?: number | null;
            /** Any Reachable Share */
            any_reachable_share?: number | null;
            /** Expected Ambiguous Share */
            expected_ambiguous_share?: number | null;
            /**
             * Exceeds Threshold
             * @default false
             */
            exceeds_threshold: boolean;
            /** Threshold */
            threshold: number;
            /** Verdict */
            verdict: string;
        };
        /** BacktestRequest */
        BacktestRequest: {
            /** Strategy Id */
            strategy_id?: string | null;
            /** Spec */
            spec?: {
                [key: string]: unknown;
            } | null;
            config: components["schemas"]["RunConfigIn"];
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            /** Reused */
            reused: boolean;
            /** Message */
            message: string;
            /** Poll Url */
            poll_url: string;
        };
        /** BatchPeriodIn */
        BatchPeriodIn: {
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
        };
        /** BatchRequest */
        BatchRequest: {
            /** Strategy Id */
            strategy_id?: string | null;
            /** Spec */
            spec?: {
                [key: string]: unknown;
            } | null;
            /** Symbols */
            symbols: string[];
            config: components["schemas"]["RunConfigIn"];
            /** Periods */
            periods?: components["schemas"]["BatchPeriodIn"][];
            /** Grid */
            grid?: {
                [key: string]: unknown[];
            } | null;
            /**
             * Consistency Metric
             * @default mean_r
             * @enum {string}
             */
            consistency_metric: "mean_r" | "expectancy" | "net_pnl" | "sharpe";
            /** Max Workers */
            max_workers?: number | null;
        };
        /** BatchResponse */
        BatchResponse: {
            /** Strategy Id */
            strategy_id: string;
            /** Symbols */
            symbols: string[];
            /** Periods */
            periods?: components["schemas"]["BatchPeriodIn"][];
            /** Grid */
            grid?: {
                [key: string]: unknown[];
            };
            /** Grid Size */
            grid_size: number;
            /** Cells */
            cells?: components["schemas"]["BatchRunOut"][];
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            consistency: components["schemas"]["ConsistencyOut"];
            /** Verdict */
            verdict: string;
            /** Warnings */
            warnings?: string[];
        };
        /** BatchRunOut */
        BatchRunOut: {
            /** Symbol */
            symbol: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Bars */
            bars: number;
            /** Trades */
            trades: number;
            /** Net Pnl */
            net_pnl?: number | null;
            /** Expectancy */
            expectancy?: number | null;
            /** Expectancy Stderr */
            expectancy_stderr?: number | null;
            /** Mean R */
            mean_r?: number | null;
            /** Mean R Stderr */
            mean_r_stderr?: number | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Profit Factor */
            profit_factor?: number | null;
            /** Win Rate */
            win_rate?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Final Equity */
            final_equity?: number | null;
            /** P Value */
            p_value?: number | null;
        };
        /**
         * BreakevenOut
         * @description Break-even win rate computed from realized trades, or why it is invalid.
         */
        BreakevenOut: {
            /** Valid */
            valid: boolean;
            /** Reason */
            reason?: string | null;
            /** Observations */
            observations: number;
            /** Breakeven Win Rate */
            breakeven_win_rate?: number | null;
            /** Realized Win Rate */
            realized_win_rate?: number | null;
            /** Delta */
            delta?: number | null;
            /** Avg Win */
            avg_win?: number | null;
            /** Avg Loss */
            avg_loss?: number | null;
            /**
             * Non Binary Trades
             * @default 0
             */
            non_binary_trades: number;
            /** Non Binary Reasons */
            non_binary_reasons?: {
                [key: string]: number;
            };
            /**
             * Variable Exits
             * @default false
             */
            variable_exits: boolean;
            /** Win Relative Std */
            win_relative_std?: number | null;
            /** Loss Relative Std */
            loss_relative_std?: number | null;
        };
        /**
         * BreakevenPriorOut
         * @description A-priori break-even win rate, from the spec and cost assumptions alone.
         */
        BreakevenPriorOut: {
            /** Valid */
            valid: boolean;
            /** Reason */
            reason?: string | null;
            /** Breakeven Win Rate */
            breakeven_win_rate?: number | null;
            /** Loss Points */
            loss_points?: number | null;
            /** Win Points */
            win_points?: number | null;
            /** Commission Points */
            commission_points?: number | null;
            /** Avg Spread Points */
            avg_spread_points?: number | null;
            /** Caveats */
            caveats?: string[];
            /**
             * Variable Exits
             * @default false
             */
            variable_exits: boolean;
            /** Stop Points Std */
            stop_points_std?: number | null;
            /** Target Points Std */
            target_points_std?: number | null;
        };
        /**
         * CompareConfigRow
         * @description One config field whose value differs between the compared runs.
         */
        CompareConfigRow: {
            /** Key */
            key: string;
            /** Values */
            values: (string | null)[];
        };
        /** CompareMetricRow */
        CompareMetricRow: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Format
             * @enum {string}
             */
            format: "pct" | "money" | "number" | "int" | "text";
            /** Higher Is Better */
            higher_is_better: boolean | null;
            /** Values */
            values: (number | null)[];
            /** Delta */
            delta: (number | null)[];
        };
        /** ComparePoint */
        ComparePoint: {
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** Values */
            values: (number | null)[];
        };
        /** CompareRequest */
        CompareRequest: {
            /** Run Ids */
            run_ids: string[];
            /**
             * Points
             * @default 1500
             */
            points: number;
            /**
             * Normalize
             * @default true
             */
            normalize: boolean;
        };
        /** CompareResponse */
        CompareResponse: {
            /** Runs */
            runs: components["schemas"]["CompareRunOut"][];
            /** Normalized */
            normalized: boolean;
            /** Axis Start */
            axis_start: string | null;
            /** Axis End */
            axis_end: string | null;
            /** Series */
            series: components["schemas"]["ComparePoint"][];
            /** Metrics */
            metrics: components["schemas"]["CompareMetricRow"][];
            /** Config Diff */
            config_diff?: components["schemas"]["CompareConfigRow"][];
            /**
             * Configs Identical
             * @default true
             */
            configs_identical: boolean;
            /** Symbol Spec Diff */
            symbol_spec_diff?: components["schemas"]["CompareConfigRow"][];
            /**
             * Symbol Specs Identical
             * @default true
             */
            symbol_specs_identical: boolean;
            /** Warnings */
            warnings?: string[];
        };
        /** CompareRunOut */
        CompareRunOut: {
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Initial Equity */
            initial_equity: number;
            /**
             * Symbol Spec Registered
             * @default true
             */
            symbol_spec_registered: boolean;
        };
        /** ConsistencyOut */
        ConsistencyOut: {
            /** Metric */
            metric: string;
            /** Observations */
            observations: number;
            /** Positive */
            positive: number;
            /** Negative */
            negative: number;
            /** Zero Or Missing */
            zero_or_missing: number;
            /** Mean */
            mean?: number | null;
            /** Median */
            median?: number | null;
            /** Std */
            std?: number | null;
            /** Stderr */
            stderr?: number | null;
            /** Minimum */
            minimum?: number | null;
            /** Maximum */
            maximum?: number | null;
            /** Sign P Value */
            sign_p_value?: number | null;
            /** Carried By One Symbol */
            carried_by_one_symbol: boolean;
            /** Dominant Symbol */
            dominant_symbol?: string | null;
            /** Verdict */
            verdict: string;
        };
        /** CoverageOut */
        CoverageOut: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Years */
            years: number[];
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Bars */
            bars: number;
            quality?: components["schemas"]["QualityOut"] | null;
        };
        /** DeflatedSharpeOut */
        DeflatedSharpeOut: {
            /** Valid */
            valid: boolean;
            /** Reason */
            reason?: string | null;
            /** Observed Sharpe Per Trade */
            observed_sharpe_per_trade?: number | null;
            /** Observed Sharpe Annualized */
            observed_sharpe_annualized?: number | null;
            /** Expected Max Sharpe */
            expected_max_sharpe?: number | null;
            /** Deflated Sharpe */
            deflated_sharpe?: number | null;
            /** Probabilistic Sharpe */
            probabilistic_sharpe?: number | null;
            /** Trials */
            trials: number;
            /** Observations */
            observations: number;
            /** Skewness */
            skewness?: number | null;
            /** Kurtosis */
            kurtosis?: number | null;
            /** Variance Across Trials */
            variance_across_trials?: number | null;
        };
        /** DegradationRowOut */
        DegradationRowOut: {
            /** Metric */
            metric: string;
            /** Observations */
            observations: number;
            /** In Sample Mean */
            in_sample_mean?: number | null;
            /** Out Of Sample Mean */
            out_of_sample_mean?: number | null;
            /** In Sample Stderr */
            in_sample_stderr?: number | null;
            /** Out Of Sample Stderr */
            out_of_sample_stderr?: number | null;
            /** Ratio */
            ratio?: number | null;
            /** Ratio Note */
            ratio_note?: string | null;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Run Id */
            run_id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** EdgeRequest */
        EdgeRequest: {
            /** Strategy Id */
            strategy_id?: string | null;
            /** Spec */
            spec?: {
                [key: string]: unknown;
            } | null;
            config: components["schemas"]["RunConfigIn"];
            /** Horizons */
            horizons?: number[] | null;
            /** Min Observations */
            min_observations?: number | null;
        };
        /** EdgeResponse */
        EdgeResponse: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Bars */
            bars: number;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Horizons */
            horizons: number[];
            /** Signals Long */
            signals_long: number;
            /** Signals Short */
            signals_short: number;
            /** Min Observations */
            min_observations: number;
            /** Significance */
            significance: number;
            /** Stats */
            stats: components["schemas"]["EdgeStatOut"][];
            /** Passed */
            passed: boolean;
            /** Verdict */
            verdict: string;
            breakeven_prior?: components["schemas"]["BreakevenPriorOut"] | null;
            ambiguity_prior?: components["schemas"]["AmbiguityPriorOut"] | null;
        };
        /** EdgeStatOut */
        EdgeStatOut: {
            /** Horizon */
            horizon: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short" | "both";
            /** Observations */
            observations: number;
            /** Mean Points */
            mean_points: number | null;
            /** Std Points */
            std_points: number | null;
            /** Stderr Points */
            stderr_points: number | null;
            /** T Stat */
            t_stat: number | null;
            /** P Value */
            p_value: number | null;
            /** Drift Baseline Points */
            drift_baseline_points: number | null;
            /** Spread Cost Points */
            spread_cost_points: number | null;
            /** Net Points */
            net_points: number | null;
            /** T Vs Cost */
            t_vs_cost: number | null;
            /** P Vs Cost */
            p_vs_cost: number | null;
            /** Beats Cost */
            beats_cost: boolean;
            /** Verdict */
            verdict: string;
        };
        /** EquityOut */
        EquityOut: {
            /** Run Id */
            run_id: string;
            /** Initial Equity */
            initial_equity: number;
            /** Total Points */
            total_points: number;
            /** Returned Points */
            returned_points: number;
            /** Downsampled */
            downsampled: boolean;
            /** Points */
            points: components["schemas"]["EquityPoint"][];
        };
        /** EquityPoint */
        EquityPoint: {
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** Equity */
            equity: number;
            /** Drawdown */
            drawdown: number;
        };
        /** ExecutionOut */
        ExecutionOut: {
            /** Signals Long */
            signals_long: number;
            /** Signals Short */
            signals_short: number;
            /** Trades */
            trades: number;
            /** Ambiguous Trades */
            ambiguous_trades: number;
            /** Gap Crossing Trades */
            gap_crossing_trades: number;
            /** Blocked */
            blocked?: {
                [key: string]: number;
            };
            /** Exit Reasons */
            exit_reasons?: {
                [key: string]: number;
            };
        };
        /** GapOut */
        GapOut: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Missing Bars */
            missing_bars: number;
        };
        /** GateRowOut */
        GateRowOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Rejected */
            rejected: number;
            /** Share */
            share: number;
            /** Exceeds Threshold */
            exceeds_threshold: boolean;
        };
        /**
         * GatesOut
         * @description Signals in, trades out, and every rejection in between.
         */
        GatesOut: {
            /** Signals */
            signals: number;
            /** Entry Attempts */
            entry_attempts: number;
            /** Executed */
            executed: number;
            /** Rejected */
            rejected: number;
            /** Executed Share */
            executed_share?: number | null;
            /** Rows */
            rows?: components["schemas"]["GateRowOut"][];
            /** Threshold */
            threshold: number;
            /** Warnings */
            warnings?: string[];
            /** Verdict */
            verdict: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramOut */
        HistogramOut: {
            /** Edges */
            edges: number[];
            /** Counts */
            counts: number[];
            /** Observed */
            observed: number;
        };
        /** MetricsOut */
        MetricsOut: {
            /** Label */
            label: string;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Days */
            days: number;
            /** Initial Equity */
            initial_equity: number;
            /** Final Equity */
            final_equity: number;
            /** Total Return */
            total_return: number | null;
            /** Annual Return */
            annual_return: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Sortino */
            sortino: number | null;
            /** Max Drawdown Money */
            max_drawdown_money: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct: number | null;
            /** Calmar */
            calmar: number | null;
            /** Trades */
            trades: number;
            /** Win Rate */
            win_rate: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Expectancy */
            expectancy: number | null;
            /**
             * Avg Duration
             * @description seconds
             */
            avg_duration?: number | null;
            /** Exposure */
            exposure: number | null;
            /** Max Losing Streak */
            max_losing_streak: number;
            /** T Stat */
            t_stat: number | null;
            /** P Value */
            p_value: number | null;
            /** R Multiples */
            r_multiples?: {
                [key: string]: number | null;
            };
            /** Costs */
            costs?: {
                [key: string]: number | null;
            };
            /**
             * Ambiguous Trades
             * @default 0
             */
            ambiguous_trades: number;
            /**
             * Gap Crossing Trades
             * @default 0
             */
            gap_crossing_trades: number;
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Drawdown Unsustainable
             * @default false
             */
            drawdown_unsustainable: boolean;
        };
        /** MultipleTestingRequest */
        MultipleTestingRequest: {
            /** Run Id */
            run_id: string;
            /**
             * Alpha
             * @default 0.05
             */
            alpha: number;
            /**
             * Grid
             * @description optional grid; without it PBO is declared not computed
             */
            grid?: {
                [key: string]: unknown[];
            } | null;
        };
        /** MultipleTestingResponse */
        MultipleTestingResponse: {
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol: string;
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /** Trials */
            trials: number;
            /** Trials Detail */
            trials_detail?: components["schemas"]["TrialOut"][];
            /** Alpha */
            alpha: number;
            deflated_sharpe: components["schemas"]["DeflatedSharpeOut"];
            /** Thresholds */
            thresholds?: components["schemas"]["ThresholdRowOut"][];
            pbo: components["schemas"]["PBOOut"];
            /** Verdict */
            verdict: string;
            /** Warnings */
            warnings?: string[];
        };
        /** OosPointOut */
        OosPointOut: {
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** Equity */
            equity: number;
        };
        /** PBOOut */
        PBOOut: {
            /** Valid */
            valid: boolean;
            /** Reason */
            reason?: string | null;
            /** Pbo */
            pbo?: number | null;
            /**
             * Splits
             * @default 0
             */
            splits: number;
            /**
             * Slices
             * @default 0
             */
            slices: number;
            /**
             * Candidates
             * @default 0
             */
            candidates: number;
            /** Logits */
            logits?: number[];
        };
        /** PermutationRequest */
        PermutationRequest: {
            /** Run Id */
            run_id: string;
            /**
             * Iterations
             * @default 1000
             */
            iterations: number;
            /** Tests */
            tests?: ("random_entries" | "permuted_returns")[];
            /**
             * Block Bars
             * @default 512
             */
            block_bars: number;
            /**
             * Seed
             * @default 12345
             */
            seed: number;
        };
        /** PermutationResponse */
        PermutationResponse: {
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol: string;
            /** Tests */
            tests?: components["schemas"]["PermutationTestOut"][];
        };
        /** PermutationStatisticOut */
        PermutationStatisticOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Observed */
            observed: number;
            /** Null Mean */
            null_mean: number;
            /** Null Std */
            null_std: number;
            /** Null P05 */
            null_p05: number;
            /** Null P50 */
            null_p50: number;
            /** Null P95 */
            null_p95: number;
            /** Percentile */
            percentile: number;
            /** P Value */
            p_value: number;
            /** Iterations */
            iterations: number;
            /** Better Than Null */
            better_than_null: boolean;
        };
        /** PermutationTestOut */
        PermutationTestOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "random_entries" | "permuted_returns";
            /** Description */
            description: string;
            /** Iterations */
            iterations: number;
            /** Iterations Requested */
            iterations_requested: number;
            /** Seed */
            seed: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Observed Trades */
            observed_trades: number;
            /** Null Trades Mean */
            null_trades_mean: number;
            /** Null Trades Std */
            null_trades_std: number;
            /** Statistics */
            statistics?: components["schemas"]["PermutationStatisticOut"][];
            histogram?: components["schemas"]["HistogramOut"] | null;
            /** Verdict */
            verdict: string;
            /** Warnings */
            warnings?: string[];
            /** Block Bars */
            block_bars?: number | null;
        };
        /** QualityOut */
        QualityOut: {
            /** Rows */
            rows: number;
            /** First Bar */
            first_bar: string | null;
            /** Last Bar */
            last_bar: string | null;
            /** Expected Bars */
            expected_bars: number;
            /** Missing Bars */
            missing_bars: number;
            /** Completeness */
            completeness: number;
            /** Gaps */
            gaps: number;
            /** Duplicate Timestamps */
            duplicate_timestamps: number;
            /** Zero Spread */
            zero_spread: number;
            /** Session Confidence */
            session_confidence: string;
            /** Text */
            text: string;
            /** Worst Gaps */
            worst_gaps?: components["schemas"]["GapOut"][];
        };
        /** ResolvedTradeOut */
        ResolvedTradeOut: {
            /** Index */
            index: number;
            /** Direction */
            direction: number;
            /**
             * Entry Time
             * Format: date-time
             */
            entry_time: string;
            /**
             * Exit Time
             * Format: date-time
             */
            exit_time: string;
            /** Original Reason */
            original_reason: string;
            /**
             * Resolution
             * @enum {string}
             */
            resolution: "stop_loss" | "take_profit" | "unresolved";
            /** Reason */
            reason?: string | null;
            /** Ticks */
            ticks: number;
            /** Stop Level */
            stop_level: number;
            /** Target Level */
            target_level: number;
            /** Original Net Pnl */
            original_net_pnl: number;
            /** Resolved Net Pnl */
            resolved_net_pnl: number;
            /** Delta */
            delta: number;
        };
        /** RunConfigIn */
        RunConfigIn: {
            /** Symbol */
            symbol: string;
            /**
             * Timeframe
             * @default M1
             */
            timeframe: string;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /**
             * Initial Equity
             * @default 100
             */
            initial_equity: number;
            /**
             * Spread Mode
             * @default per_bar
             * @enum {string}
             */
            spread_mode: "per_bar" | "fixed" | "quantile";
            /** Spread Value */
            spread_value?: number | null;
            /**
             * Commission Per Lot Per Side
             * @default 0
             */
            commission_per_lot_per_side: number;
            /**
             * Swap Mode
             * @default points
             * @enum {string}
             */
            swap_mode: "points" | "money" | "none";
            /**
             * Session Threshold
             * @default 0.5
             */
            session_threshold: number;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Engine Version */
            engine_version: string;
            /** Spec Hash */
            spec_hash: string;
            /** Data Hash */
            data_hash: string;
            /** Symbol Spec Hash */
            symbol_spec_hash?: string | null;
            /** Bars */
            bars: number;
            /** Data Start */
            data_start: string | null;
            /** Data End */
            data_end: string | null;
            /** Error */
            error: string | null;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
            /** Config */
            config: {
                [key: string]: unknown;
            };
            strategy?: components["schemas"]["MetricsOut"] | null;
            benchmark?: components["schemas"]["MetricsOut"] | null;
            breakeven?: components["schemas"]["BreakevenOut"] | null;
            execution?: components["schemas"]["ExecutionOut"] | null;
            uncertainty?: components["schemas"]["UncertaintyOut"] | null;
            gates?: components["schemas"]["GatesOut"] | null;
            symbol_spec?: components["schemas"]["SymbolSpecOut"] | null;
            /** Symbol Spec Read At */
            symbol_spec_read_at?: string | null;
            /**
             * Symbol Spec Registered
             * @default true
             */
            symbol_spec_registered: boolean;
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Strategy Id */
            strategy_id: string;
            /** Strategy Name */
            strategy_name: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Data Start */
            data_start: string | null;
            /** Data End */
            data_end: string | null;
            /** Bars */
            bars: number;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Error */
            error: string | null;
            /** Trades */
            trades: number | null;
            /** Final Equity */
            final_equity: number | null;
            /** Total Return */
            total_return: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Ambiguous Trades */
            ambiguous_trades: number | null;
        };
        /** ScreenCellOut */
        ScreenCellOut: {
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Stage Reached */
            stage_reached: string;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Gate Passed */
            gate_passed?: boolean | null;
            /** Gate Signals */
            gate_signals?: number | null;
            /** Gate Best Net Points */
            gate_best_net_points?: number | null;
            /** Gate Best P Value */
            gate_best_p_value?: number | null;
            /** Gate Verdict */
            gate_verdict?: string | null;
            /** Expected Ambiguous Share */
            expected_ambiguous_share?: number | null;
            /** Ambiguity Flag */
            ambiguity_flag?: boolean | null;
            /** Run Id */
            run_id?: string | null;
            /** Bars */
            bars?: number | null;
            /** Trades */
            trades?: number | null;
            /** Net Pnl */
            net_pnl?: number | null;
            /** Final Equity */
            final_equity?: number | null;
            /** Sharpe Per Trade */
            sharpe_per_trade?: number | null;
            /** Sharpe Annualized */
            sharpe_annualized?: number | null;
            /** Mean R */
            mean_r?: number | null;
            /** Win Rate */
            win_rate?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** P Value */
            p_value?: number | null;
            /** Ambiguous Share */
            ambiguous_share?: number | null;
            /** Band Money */
            band_money?: number | null;
            /** Top Gate */
            top_gate?: string | null;
            /** Top Gate Share */
            top_gate_share?: number | null;
            /** Gate Warnings */
            gate_warnings?: string[];
            /** Permutation P Value */
            permutation_p_value?: number | null;
            /** Permutation Kind */
            permutation_kind?: string | null;
            /** Permutation Iterations */
            permutation_iterations?: number | null;
        };
        /**
         * ScreenJobOut
         * @description A campaign takes minutes: it is a job, polled, not a blocked request.
         */
        ScreenJobOut: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Completed Cells
             * @default 0
             */
            completed_cells: number;
            /**
             * Total Cells
             * @default 0
             */
            total_cells: number;
            /** Current */
            current?: string | null;
            /** Error */
            error?: string | null;
            report?: components["schemas"]["ScreenReportOut"] | null;
        };
        /** ScreenReportOut */
        ScreenReportOut: {
            /** Strategies */
            strategies: string[];
            /** Symbols */
            symbols: string[];
            /** Timeframes */
            timeframes: string[];
            /** Period Start */
            period_start?: string | null;
            /** Period End */
            period_end?: string | null;
            /** Initial Equity */
            initial_equity: number;
            /** Cells */
            cells: components["schemas"]["ScreenCellOut"][];
            panel: components["schemas"]["TrialPanelOut"];
            /** Thresholds */
            thresholds?: components["schemas"]["ThresholdRowOut"][];
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Engine Version */
            engine_version: string;
            /** Verdict */
            verdict: string;
            /** Warnings */
            warnings?: string[];
        };
        /** ScreenRequest */
        ScreenRequest: {
            /** Strategy Ids */
            strategy_ids: string[];
            /** Symbols */
            symbols: string[];
            /** Timeframes */
            timeframes: string[];
            config: components["schemas"]["RunConfigIn"];
            /**
             * Min Trades
             * @default 30
             */
            min_trades: number;
            /**
             * Permutation Iterations
             * @default 200
             */
            permutation_iterations: number;
        };
        /** StabilityRowOut */
        StabilityRowOut: {
            /** Parameter */
            parameter: string;
            /** Observations */
            observations: number;
            /** Distinct Values */
            distinct_values: number;
            /** Chosen */
            chosen: string[];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Mode */
            mode: string;
            /** Mode Share */
            mode_share: number;
        };
        /** StrategyOut */
        StrategyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** File */
            file: string;
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** SymbolListOut */
        SymbolListOut: {
            /** Symbols */
            symbols: components["schemas"]["SymbolSpecOut"][];
            /**
             * Source
             * @enum {string}
             */
            source: "terminal" | "cache";
            /** Server Timezone */
            server_timezone?: string | null;
            /**
             * Cached Symbols
             * @description symbols with data already in the local cache
             */
            cached_symbols?: string[];
        };
        /** SymbolSpecOut */
        SymbolSpecOut: {
            /** Name */
            name: string;
            /** Point */
            point: number;
            /** Digits */
            digits: number;
            /** Contract Size */
            contract_size: number;
            /** Tick Value */
            tick_value: number;
            /** Tick Size */
            tick_size: number;
            /** Volume Min */
            volume_min: number;
            /** Volume Max */
            volume_max: number;
            /** Volume Step */
            volume_step: number;
            /** Swap Long */
            swap_long: number;
            /** Swap Short */
            swap_short: number;
            /** Currency Profit */
            currency_profit: string;
            /** Trade Mode */
            trade_mode: string;
        };
        /** ThresholdRowOut */
        ThresholdRowOut: {
            /** Run Id */
            run_id: string;
            /** Strategy Id */
            strategy_id: string;
            /** P Value */
            p_value: number;
            /** Rank */
            rank: number;
            /** Bonferroni Threshold */
            bonferroni_threshold: number;
            /** Benjamini Hochberg Threshold */
            benjamini_hochberg_threshold: number;
            /** Passes Bonferroni */
            passes_bonferroni: boolean;
            /** Passes Benjamini Hochberg */
            passes_benjamini_hochberg: boolean;
            /** Mean Pnl Positive */
            mean_pnl_positive: boolean;
        };
        /** TickResolveRequest */
        TickResolveRequest: {
            /** Run Id */
            run_id: string;
        };
        /** TickResolveResponse */
        TickResolveResponse: {
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol: string;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Ambiguous Trades */
            ambiguous_trades: number;
            /** Resolved */
            resolved: number;
            /** Unresolved */
            unresolved: number;
            /** Resolved To Take Profit */
            resolved_to_take_profit: number;
            /** Resolved To Stop Loss */
            resolved_to_stop_loss: number;
            /** Trades */
            trades?: components["schemas"]["ResolvedTradeOut"][];
            /** Original Net Pnl */
            original_net_pnl: number;
            /** Resolved Net Pnl */
            resolved_net_pnl: number;
            /** Delta Net Pnl */
            delta_net_pnl: number;
            /** Original Final Equity */
            original_final_equity?: number | null;
            /** Resolved Final Equity */
            resolved_final_equity?: number | null;
            /** Original Win Rate */
            original_win_rate?: number | null;
            /** Resolved Win Rate */
            resolved_win_rate?: number | null;
            /** Verdict */
            verdict: string;
            /** Warnings */
            warnings?: string[];
        };
        /** TradeOut */
        TradeOut: {
            /** Index */
            index: number;
            /** Direction */
            direction: number;
            /**
             * Entry Time
             * Format: date-time
             */
            entry_time: string;
            /** Entry Price */
            entry_price: number;
            /** Stop Level */
            stop_level?: number | null;
            /** Target Level */
            target_level?: number | null;
            /**
             * Exit Time
             * Format: date-time
             */
            exit_time: string;
            /** Exit Price */
            exit_price: number;
            /** Exit Reason */
            exit_reason: string;
            /** Lots */
            lots: number;
            /** Bars Held */
            bars_held: number;
            /** Session Bars Held */
            session_bars_held: number;
            /** Gross Pnl */
            gross_pnl: number;
            /** Spread Points */
            spread_points: number;
            /** Spread Cost */
            spread_cost: number;
            /** Commission */
            commission: number;
            /** Swap */
            swap: number;
            /** Net Pnl */
            net_pnl: number;
            /** Risk Money */
            risk_money: number | null;
            /** R Multiple */
            r_multiple: number | null;
            /** Ambiguous */
            ambiguous: boolean;
            /** Crossed Gap */
            crossed_gap: boolean;
        };
        /** TradesOut */
        TradesOut: {
            /** Run Id */
            run_id: string;
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Ambiguous Total */
            ambiguous_total: number;
            /** Items */
            items: components["schemas"]["TradeOut"][];
        };
        /** TrialOut */
        TrialOut: {
            /** Run Id */
            run_id: string;
            /** Strategy Id */
            strategy_id: string;
            /** Spec Hash */
            spec_hash: string;
            /** Trades */
            trades: number;
            /** Sharpe Per Trade */
            sharpe_per_trade: number;
            /** Net Pnl */
            net_pnl: number;
            /** P Value */
            p_value?: number | null;
        };
        /**
         * TrialPanelOut
         * @description The correction owed for the size of the campaign.
         */
        TrialPanelOut: {
            /** Attempts */
            attempts: number;
            /** Cells Backtested */
            cells_backtested: number;
            /** Cells Permuted */
            cells_permuted: number;
            /** Sharpes Observed */
            sharpes_observed: number;
            /** Variance Across Trials */
            variance_across_trials?: number | null;
            /** Expected Max Sharpe */
            expected_max_sharpe?: number | null;
            /** Required Sharpe Per Trade */
            required_sharpe_per_trade?: number | null;
            /** Confidence */
            confidence: number;
            /** Alpha */
            alpha: number;
            /** Bonferroni Threshold */
            bonferroni_threshold?: number | null;
            /** Best Strategy */
            best_strategy?: string | null;
            /** Best Sharpe Per Trade */
            best_sharpe_per_trade?: number | null;
            /** Best Clears Required */
            best_clears_required?: boolean | null;
            /** Survivors After Correction */
            survivors_after_correction: number;
            /** Verdict */
            verdict: string;
            /** Assumptions */
            assumptions?: string[];
        };
        /**
         * UncertaintyOut
         * @description Conservative and optimistic readings of the same run (ambiguous trades).
         */
        UncertaintyOut: {
            /** Trades */
            trades: number;
            /** Ambiguous Trades */
            ambiguous_trades: number;
            /** Ambiguous Share */
            ambiguous_share: number;
            /** Resolvable */
            resolvable: boolean;
            /** Reason */
            reason?: string | null;
            /** Conservative Net Pnl */
            conservative_net_pnl: number;
            /** Optimistic Net Pnl */
            optimistic_net_pnl: number;
            /** Band Money */
            band_money: number;
            /** Conservative Final Equity */
            conservative_final_equity?: number | null;
            /** Optimistic Final Equity */
            optimistic_final_equity?: number | null;
            /** Band Equity Pct */
            band_equity_pct?: number | null;
            /** Conservative Win Rate */
            conservative_win_rate?: number | null;
            /** Optimistic Win Rate */
            optimistic_win_rate?: number | null;
            /**
             * Exceeds Threshold
             * @default false
             */
            exceeds_threshold: boolean;
            /** Threshold */
            threshold: number;
            /** Verdict */
            verdict: string;
            /** Warnings */
            warnings?: string[];
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Spec */
            spec: {
                [key: string]: unknown;
            };
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Valid */
            valid: boolean;
            /** Message */
            message: string;
            /** Errors */
            errors?: string[];
            /** Normalized */
            normalized?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WalkForwardMetricsOut
         * @description Metrics of one leg. Extra keys are allowed: the engine may add more.
         */
        WalkForwardMetricsOut: {
            /** Trades */
            trades?: number | null;
            /** Net Pnl */
            net_pnl?: number | null;
            /** Total Return */
            total_return?: number | null;
            /** Sharpe */
            sharpe?: number | null;
            /** Profit Factor */
            profit_factor?: number | null;
            /** Win Rate */
            win_rate?: number | null;
            /** Expectancy */
            expectancy?: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct?: number | null;
            /** Final Equity */
            final_equity?: number | null;
            /** Initial Equity */
            initial_equity?: number | null;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** WalkForwardRequest */
        WalkForwardRequest: {
            /** Run Id */
            run_id: string;
            /**
             * Mode
             * @default rolling
             * @enum {string}
             */
            mode: "rolling" | "anchored";
            /**
             * Train Days
             * @default 90
             */
            train_days: number;
            /**
             * Test Days
             * @default 30
             */
            test_days: number;
            /**
             * Min Train Trades
             * @default 30
             */
            min_train_trades: number;
            /**
             * Objective
             * @default net_pnl
             * @enum {string}
             */
            objective: "net_pnl" | "sharpe" | "profit_factor" | "expectancy";
            /**
             * Grid
             * @description dotted spec path -> values to try, e.g. exit.stop_loss.value: [100, 150, 200]
             */
            grid?: {
                [key: string]: unknown[];
            } | null;
        };
        /** WalkForwardResponse */
        WalkForwardResponse: {
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "rolling" | "anchored";
            /** Train Days */
            train_days: number;
            /** Test Days */
            test_days: number;
            /** Min Train Trades */
            min_train_trades: number;
            /** Objective */
            objective: string;
            /** Embargo Minutes */
            embargo_minutes: number;
            /** Grid */
            grid?: {
                [key: string]: unknown[];
            };
            /** Grid Size */
            grid_size: number;
            /** Optimized */
            optimized: boolean;
            /** Windows */
            windows?: components["schemas"]["WalkForwardWindowOut"][];
            /** Windows Evaluated */
            windows_evaluated: number;
            /** Windows Skipped */
            windows_skipped: number;
            /** Oos Trades */
            oos_trades: number;
            oos_metrics?: components["schemas"]["WalkForwardMetricsOut"] | null;
            /** Oos Curve */
            oos_curve?: components["schemas"]["OosPointOut"][];
            /** Degradation */
            degradation?: components["schemas"]["DegradationRowOut"][];
            /** Parameter Stability */
            parameter_stability?: components["schemas"]["StabilityRowOut"][];
            /** Verdict */
            verdict: string;
            /** Warnings */
            warnings?: string[];
        };
        /** WalkForwardWindowOut */
        WalkForwardWindowOut: {
            /** Index */
            index: number;
            /**
             * Train Start
             * Format: date-time
             */
            train_start: string;
            /**
             * Train End
             * Format: date-time
             */
            train_end: string;
            /**
             * Test Start
             * Format: date-time
             */
            test_start: string;
            /**
             * Test End
             * Format: date-time
             */
            test_end: string;
            /** Embargo Minutes */
            embargo_minutes: number;
            /** Skipped */
            skipped: boolean;
            /** Skip Reason */
            skip_reason?: string | null;
            /** Candidates Evaluated */
            candidates_evaluated: number;
            /** Chosen Params */
            chosen_params?: {
                [key: string]: unknown;
            };
            /** Train Trades */
            train_trades: number;
            /** Test Trades */
            test_trades: number;
            train_metrics?: components["schemas"]["WalkForwardMetricsOut"] | null;
            test_metrics?: components["schemas"]["WalkForwardMetricsOut"] | null;
            /** Equity Start */
            equity_start?: number | null;
            /** Equity End */
            equity_end?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_symbols_api_symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolListOut"];
                };
            };
        };
    };
    get_coverage_api_symbols__symbol__coverage_get: {
        parameters: {
            query?: {
                timeframe?: string;
                /** @description also compute the quality report */
                quality?: boolean;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
        };
    };
    get_strategy_api_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_strategy_api_strategies_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_edge_api_edge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_backtest_api_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                strategy_id?: string | null;
                status?: ("running" | "done" | "error") | null;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equity_api_runs__run_id__equity_get: {
        parameters: {
            query?: {
                points?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trades_api_runs__run_id__trades_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                ambiguous_only?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_api_runs_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_walkforward_api_validation_walkforward_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalkForwardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalkForwardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_permutation_api_validation_permutation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermutationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_multiple_testing_api_validation_multiple_testing_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MultipleTestingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultipleTestingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_tick_resolve_api_validation_tick_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TickResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_batch_api_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_screen_api_screen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screen_api_screen__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
