/**
 * The product's name and its mark.
 *
 * `core/product.py` holds the same two strings for the Python half; they are
 * short enough that a build step to share them would cost more than it saves,
 * and both files say so.
 *
 * The mark is generated by `scripts/make_icons.py`, which is also what writes
 * `brand/falsify.ico` and `ui/public/favicon.svg`. The geometry is repeated
 * here as JSX rather than fetched, because the header must not wait on a
 * network request to draw a logo - and in the desktop build there is no
 * server to ask.
 */
export const PRODUCT_NAME = "Falsify";
export const TAGLINE = "A backtesting engine that tries to prove your strategy wrong.";

/** An F whose crossbar overshoots the stem and leans, so it reads as struck. */
export function Mark({ size = 20 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 32 32"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <rect x="10" y="3" width="4.5" height="26" />
      <rect x="10" y="3" width="17" height="4.5" />
      <rect x="2.5" y="16.75" width="22" height="4.5" transform="rotate(-30 13.5 19)" />
    </svg>
  );
}

/** Mark plus wordmark. Links home, which is the Run page. */
export function Brand() {
  return (
    <a className="brand" href="#/" aria-label={`${PRODUCT_NAME} — home`}>
      <Mark size={20} />
      <span className="word">FALSIFY</span>
      <span className="where">· local</span>
    </a>
  );
}
